#-------------------------- ACTIVIDAD 1---------------------------------
# name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: 'Actividades/Actividad 1-CC3S2/devops-practice/'

    - name: Run tests
      run: npm test
      working-directory: 'Actividades/Actividad 1-CC3S2/devops-practice/'


# name: CI/CD Pipeline
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
 
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '14'

#     - name: Change to project directory
#       run: cd 'Actividades/Actividad 1-CC3S2/devops-practice/'

#     - name: Install dependencies
#       run: npm install

#     - name: Run tests
#       run: npm test
#       working-directory: 'Actividades/Actividad 1-CC3S2/devops-practice/'  
   
#     - name: Build Docker image
#       run: docker build -t devops-practice .   
#       working-directory: 'Actividades/Actividad 1-CC3S2/devops-practice/'  
        
#     - name: Run Docker container
#       run: docker run -d -p 3000:3000 devops-practice
#       working-directory: 'Actividades/Actividad 1-CC3S2/devops-practice/'  

#-------------------------- ACTIVIDAD 2---------------------------------
# name: CI Pipeline
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
 
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '14'

#     - name: Install dependencies
#       run: npm install
#       working-directory: 'Actividades/Actividad 2-CC3S2/devops-practice/'  

#     - name: Run tests
#       run: npm test
#       working-directory: 'Actividades/Actividad 2-CC3S2/devops-practice/'  
   
#     - name: Run security audit
#       run: npm audit   
#       working-directory: 'Actividades/Actividad 2-CC3S2/devops-practice/'  
